name: 'SonarQube Scan'
description: 'Scan your code with SonarQube to detect bugs, vulnerabilities and code smells.'
branding:
  icon: 'check'
  color: 'green'
runs:
  using: 'docker'
  image: 'Dockerfile'
